# 공통: personas.yaml 파일과 기본 그룹 지정 가능
personas_file: personas.yaml
personas_group: default   # 기본값(잡에서 재정의 가능)

jobs:
  - name: morning-publish
    system_prompt: "당신은 유능한 AI 어시스턴트입니다."
    personas_group: default      # ← 이 잡은 음성 포함 베이직 체인
    style: basic                 # basic|emotional
    include_voice: true
    tts_provider: elevenlabs     # elevenlabs|polly
    tts_template: korean_female
    polly_voice_key: Seoyeon
    subtitle_lang: ko
    bgm_path: assets/bgm.mp3     # 없으면 생략 가능
    upload: true
    out_dir: assets/auto/morning

  - name: night-emotional
    system_prompt: "당신은 감성 카피라이터입니다."
    personas_group: emotional    # ← 이 잡은 감성 텍스트 체인
    style: emotional             # 무성, dark text 비디오
    include_voice: false
    subtitle_lang: ko
    bgm_path: assets/bgm_soft.mp3
    upload: false
    out_dir: assets/auto/night
